# Generated by Django 3.0 on 2020-12-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=700)),
                ('git_hub_link', models.TextField(blank=True, max_length=1000)),
                ('proj_link', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
